apiVersion: v1
kind: Service
metadata:
  name: kodbox-svc
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: kodbox-svc
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kodbox
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kodbox-svc
  template:
    metadata:
      labels:
        app: kodbox-svc
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chmod -f -R 777 /var/www/html"]
        volumeMounts:
        - name: kodbox-data
          mountPath: /var/www/html
      containers:
        - name: kodbox
          image: kodcloud/kodbox:v1.4505
          command:
          - "/bin/sh"
          - "-c"
          - |
            if [ -d "/var/www/html/config" ]; then
              echo "config exist, use old config"
            else
              /entrypoint.sh
            fi
            /usr/bin/supervisord -n -c /etc/supervisord.conf
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
          volumeMounts:
            - name: kodbox-data
              mountPath: /var/www/html
  volumeClaimTemplates:
  - metadata:
      name: kodbox-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: nfs
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kodbox-nodeport-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: kodbox